// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QDP.Entity;

namespace QDP.Entity.Migrations
{
    [DbContext(typeof(QDPDBContext))]
    partial class QDPDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QDP.Entity.BuildingSheet", b =>
                {
                    b.Property<Guid>("bs_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("bs_constructionarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bs_floorheight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bs_formats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bs_housedescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bs_remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bs_totalheight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bs_totalhousehold")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bs_ID");

                    b.ToTable("buildingSheets");
                });

            modelBuilder.Entity("QDP.Entity.CostSummary", b =>
                {
                    b.Property<Guid>("cs_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cs_costaccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cs_garage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cs_highclass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cs_subjectcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cs_totalcost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cs_unilateralcost")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cs_ID");

                    b.ToTable("costSummaries");
                });

            modelBuilder.Entity("QDP.Entity.HighClass", b =>
                {
                    b.Property<Guid>("hc_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MyProhc_numberperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hc_Indicatordescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hc_costaccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hc_subjectcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hc_ID");

                    b.ToTable("highClasses");
                });

            modelBuilder.Entity("QDP.Entity.Project", b =>
                {
                    b.Property<Guid>("p_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("P_foundationtreatmenttype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_Nonairdefensemechanicalparkingspace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_airdefensemechanicalparkingspace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_airdefenseundergroundparkingspace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_basementarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_basictype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_brancharea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_branchheight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_branchnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_constructionareaofgroundgarden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_endtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_fararea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_garageheight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_garagenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_groundgreenarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_highclassarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_highclassheight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_highclassnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_ismeasuresfee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_nonairdefenseundergroundparkingspace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_othergardenconstructionarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_othergreenarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_otherroadarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_overtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_projectcategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_seismicfortificationintensity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_settlementmethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_starttime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_structuretype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_surfaceroadarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_taxtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_totalarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_totalheight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_totalhousehold")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_valuationbasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_windpressureame")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("p_ID");

                    b.ToTable("projects");
                });
#pragma warning restore 612, 618
        }
    }
}
